export const WS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_CONNECTION_END = 'WS_CONNECTION_END';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_FAILED = 'WS_CONNECTION_FAILED';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS = 'WS_GET_ORDERS';
export const WS_SEND_ORDERS = 'WS_GET_ORDERS';

export const wsActions = {
  wsInit: WS_CONNECTION_START,
  wsEnd: WS_CONNECTION_END,
  onOpen: WS_CONNECTION_SUCCESS,
  onClose: WS_CONNECTION_CLOSED,
  onError: WS_CONNECTION_FAILED,
  onMessage: WS_GET_ORDERS,
  sendMessage: WS_SEND_ORDERS
};