export const WS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_FAILED = 'WS_CONNECTION_FAILED';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS = 'WS_GET_ORDERS';

export const wsActions = {
  wsInit: WS_CONNECTION_START,
  onopen: WS_CONNECTION_SUCCESS,
  onclose: WS_CONNECTION_CLOSED,
  onerror: WS_CONNECTION_FAILED,
  onmessage: WS_GET_ORDERS,

};